### ISSUE TITLE
[GC Express]: 

### ISSUE THREAD

**Issue by marinadistefano** [clingen-data-model/clingen-search#781]
### Requester Name

Marina DiStefano

### Requester Contact Info

mdistefa@broadinstitute.org

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_3212

### Additional Notes

Hi Marina,

 

 

Thank you so much for sharing this information with us.

 

Yes, the leadership team of HC-GCEP definitely agreed with Ada’s suggestions. We also think to unpublish the DICER1/PPB gene curation and to consider adjusting the dosage curation from PPB to DICER1-related tumor predisposition both make sense to us.

 

Best,

Sheng-An

 

-- 

Sheng-An Yang, PhD

Staff Scientist, ClinGen

Texas Children's Hospital

Department of Pediatrics, Baylor College of Medicine

**Comment by toneillbroad** [comment]
Deployed removal to stage and production. Confirmed removal.
