### ISSUE TITLE
[GC Express]: GJB2 - hearing loss, autosomal recessive

### ISSUE THREAD

**Issue by RyanFWebb** [clingen-data-model/clingen-search#789]
### Requester Name

Ryan Webb

### Requester Contact Info

rwebb@broadinstitute.org

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8399

### Additional Notes

This record is outdated and was submitted using ClinGen SOPv4. We have a new GCI entry for GJB2 and AR nonsyndromic genetic hearing loss, but are waiting to enter it until the old entry on the ClinGen website is removed.

**Comment by toneillbroad** [comment]
Removed on stage and prod and validated removal.
