### ISSUE TITLE
[GC Express]: 

### ISSUE THREAD

**Issue by jasminebro** [clingen-data-model/clingen-search#790]
### Requester Name

Jasmine Baker_BCMClinGen_HCGCEP

### Requester Contact Info

Jasmine.Baker@bcm.edu

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10080

### Additional Notes

I have multiple curations that need to be removed. 

<google-sheets-html-origin><style type="text/css"></style>
Date of Most Recent Curation | Clincalgenome.org Update Needed | Gene | URL
-- | -- | -- | --
pending  lumped curation completion | remove 2017 familial ovarian cancer | ATM | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10080
pending  lumped curation completion | remove 2017 hereditary breast carcinoma | ATM | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9908
pending curation completion | remove 2017 hereditary nonpolyposis colon cancer | ATM | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9861
2024 | remove 2017 hereditary breast carcinoma | BARD1 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10081
2024 | remove 2017 familial ovarian cancer | BARD1 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9909
2017 | remove 2017 hereditary nonpolyposis colon cancer curation | BARD1 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8430
2024 | remove 2017 breast-ovarian cancer, familial, susceptibility to, 1 | BRCA1 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9972
2024 | remove 2017 breast-ovarian cancer, familial, susceptibility to, 2 | BRCA2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8397
pending curation completion | remove 2016 hereditary breast carcinoma | CHEK2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8522
pending curation completion | remove 2016 familial ovarian cancer | CHEK2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8523
2024 | remove 2016 hereditary breast cancer | PALB2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_3213
2024 | remove 2017 familial ovarian cancer | PALB2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_9940
pending curation completion | remove 2018 hereditary nonpolyposis colon cancer | PALB2 | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_10073
2024 | remove 2017 hereditary breast cancer | RAD51C | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8697
2014 | remove 2017 hereditary breast cancer | RAD51D | https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_3215

**Comment by toneillbroad** [comment]
Completed and successfully tested against stage and production environments on 9/23/24.
