### ISSUE TITLE
[GC Express]: Remove a GC express entry for ADCY1

### ISSUE THREAD

**Issue by kezang-tshering** [clingen-data-model/clingen-search#791]
### Requester Name

Kezang Tshering

### Requester Contact Info

ktsherin@broadinstitute.org

### GC Express Entry Website URL

https://search.clinicalgenome.org/kb/gene-validity/CGGCIEX:assertion_8152

**Comment by toneillbroad** [comment]
Removed curation and tested on stage and production.
